---
- name: Install pip
  apt:
    name: ['python3-pip', 'python-pip']
    state: present
  become: yes

- name: Pip install required modules
  pip:
    name: "{{ flask_packages }}"
    executable: pip3

- name: Copy service configuration
  template:
    src: files/hello-world.service.j2
    dest: /etc/systemd/system/hello-world.service
  become: yes

- name: Make sure app diectory exists
  file:
    path: "{{ app_path }}"
    state: directory

- name: Copy app.py file to app diectory
  copy:
    src: files/app.py
    dest: "{{ app_path }}/app.py"
  notify: restart hello-world

- name: Make sure our server is running
  service:
    name: hello-world
    state: started
    enabled: yes
  become: yes
